[package]
name = "risc-v-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
glob = "0.3.0"
object = "0.30.0"
